source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ButtonBar' do
  pod 'LKTabBarController', :path => "../"
end

target 'ButtonBarTests' do
  pod 'LKTabBarController', :path => "../"
end

target 'ButtonBarUITests' do

end

