# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ButtonBar' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'LKTabBarController', :path => "../"
end

target 'ButtonBarTests' do

end

target 'ButtonBarUITests' do

end

